config/routes.rb
Rails.application.routes.draw do 
  resources :projects
  resources :posts 
  resources :comments, :except => [:index]
  resources :users, :except => [:index]

  get '/' => 'users#login'

  post '/login' => 'users#login_post'

  get '/logout' => 'users#logout'

  get '/post/:id/likes' => 'posts#like', as: :like

  get '/post/:id/dislikes' => 'posts#dislike', as: :dislike

  get '/posts_ordered_by_likes' => 'posts#order_by_like'

  get '/posts_ordered_by_comments' => 'posts#order_by_comment'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :posts
	has_many :comments

	def full_name
		"#{first_name} #{last_name}"
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user

  	if session[:user_id]
  		@user ||= User.find(session[:user_id])
  	end
  end

  
  helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show

  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_reply, :post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if current_user == nil
      redirect_to '/' 
    end

    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @new_comment = Comment.new    
  end

  def like
      @post = Post.find(params[:id])
      @post.likes +=1
      @post.save
      redirect_to post_url
  end

  def dislike
      @post = Post.find(params[:id])
      @post.likes -= 1
      @post.save
      redirect_to post_url
  end

  def order_by_like
      @posts = Post.order(likes: :desc)
      render :index
  end

  def order_by_comment
      @posts = Post.joins(:comments).group("posts.id").order("count(comments) desc")
      render :index
  end

  # GET /posts/new
  def new
      @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :content, :likes, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index

    if current_user == nil
      redirect_to '/'
    end
    @users = User.all
  end

  def  login
   #THIS GETS THE LOG IN FORM, AND THAT IS all
   if current_user
      redirect_to posts_path
   else
    render :login
   end
  end

  def logout
    session[:user_id]= nil
    redirect_to '/'
  end

  def login_post
    @user = User.find_by({email: params[:email]})
    if @user
      #proceed with the login
      if @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to '/posts#index'
      else
        redirect_to '/'
      end
    else
      redirect_to '/'
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "Thank you for registering for Chit-Chat Forum" }
        format.json { render :show, status: :created, location: @user }
        session[:user_id] = @user.id
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_reply %><br>
    <%= f.text_area :post_reply %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing Comments</h1>

<table>
  <thead>
    <tr> 
      <th>Post reply</th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_reply %></td>
        <td><%= comment.post.title %></td>
        <td><%= "#{comment.user.first_name} #{comment.user.last_name}" %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <strong>Post:</strong>
  <%= "#{@comment.post.title}" %>
</p>

<p>
  <strong>Post reply:</strong>
  <%= @comment.post_reply %>
</p>

<p>
  <strong>Posted By:</strong>
  <%= "#{@comment.user.first_name} #{@comment.user.last_name}" %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chit-Chat Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Advent+Pro' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Dosis' rel='stylesheet' type='text/css'>
</head>
	
<body>
<div class="container" id="navBar">
	<div class="row">

		<div class="col-md-10">
			<h1 id="forumTitle">Chit-Chat Forum</h1>
		</div>

		<div class="col-md-2" id= "homeNav">
			<% if current_user %>
				<strong>Hey there, <%=  current_user.first_name%></strong></br>
			<% elsif current_user == nil%>
			<% end %>

			<% if current_user == nil %>
			<% elsif current_user %>
				<%= link_to "Logout", logout_path%>
			<% end %>
		</div>

	</div>
</div>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row sortButtons">
      <a class= "btn btn-success"href="/posts/new">Create A New Post</a>
  </div>
</div>

<div class="container postIndexList">
  <div class="row postIndexTopBar">
      <h3 class="col-xs-8">Lets Chit-Chat!</h3>
       <a class="btn btn-success col-xs-2" href="/posts_ordered_by_likes">Sort By Likes</a>
      <a class="btn btn-danger col-xs-2" href="/posts_ordered_by_comments">Sort By comments</a>
  </div>

  <div class="row">
      <div class="col-md-12 postIndexListTable">
      
          <% @posts.each do |post| %>
          
              <div class="container postSingle">
                <div class="row ">
                  <h5 class="col-md-5"><%= link_to post.title, post %></h5>
                  <h5 class="col-md-3"><%= post.user.full_name %></h5>
                  <h5 class="col-md-2">Likes: <%= post.likes %></h5>
                  <h5 class="col-md-2">Comments: <%= post.comments.length%></h5>
                </div>
              </div>
         
          <% end %>
      </div>
   
  </div>
</div>

app/views/posts/new.html.erb
<div class = "container newPost">
	<div class = "row">
		<div class="col-md-12">
			<h1>New Post</h1>
			<%= render 'form' %>
			<button>
				<%= link_to 'Back', posts_path %>
			</button>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container postShow">

  <div class="btn-group" role="group">
      <div class="postShowButtons btn-lg">
        <button type="button"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span><%= link_to ' Like', like_path(@post)%>
        </button>
        <button type="button"><span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
          <%= link_to ' Dislike', dislike_path(@post)%>
        </button>
        <strong>Likes:<%= @post.likes %></strong>
        <button type="button">
          <%= link_to ' Go Back', posts_path %>
        </button> 
      </div>
  </div>

  
    <div class="row postShowSections">
     
      <div class="col-md-6">
        <div class="postShowTitleSection">
        <h1>
          <%= @post.title %>
        </h1>
        <hr class="hrBar">
        <strong>
            Created By : <%= @post.user.full_name %>
        </strong>
        <h5>
          <%= @post.content %>
        </h5>
        </div>
      </div>

      <div class="col-md-6">
        <div class="postShowCommentSection">

        <h1>Chit-Comments</h1>
        <hr class="hrBar">
        
        <div class="postCommentBox">
          <% @post.comments.each do |reply| %>
            <p class="postComments"><%= reply.post_reply %></p>
          <% end %>
        </div>
          
      
          
        <%= form_for(@new_comment) do |f| %>
          <% if @new_comment.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@new_comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
              <ul>
                <% @new_comment.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
           <!--  <%= f.label :post_reply %><br> -->
            <%= f.text_area :post_reply %>
          </div> 
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.hidden_field :user_id, value: @post.user.id %>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
        </div>
      </div>
     
    </div>
 
</div>

app/views/users/_form.html.erb
    <div class="col-md-12">
      <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :first_name %><br>
          <%= f.text_field :first_name %>
        </div>
        <div class="field">
          <%= f.label :last_name %><br>
          <%= f.text_field :last_name %>
        </div>
        <div class="field">
          <%= f.label :email %><br>
          <%= f.text_field :email %>
        </div>
        <div class="field">
          <%= f.label :password %><br>
          <%= f.password_field :password %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
    </div>

app/views/users/edit.html.erb
<div class="container" id="userEdit">
	<div class="row">
		<h1>Editing User</h1>
		<%= render 'form' %>
		<%= link_to 'Show', @user %> |
		<%= link_to 'Back', users_path %>
	</div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<div class="container" id="userLogin">
	<div class="row">
		<div class="col-md-12">
			<h1 class= "loginTitle">Log In</h1>
			<form action="/login" method="post">
				<div class="email">
					<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
					<label>Email:</label></br>
					<input type ="email" name= "email" placeholder="Username">
				</div>
				<div class="password">
					<label>Password:</label></br>
					<input type="password" name="password" placeholder="Password">
				</div>
					<input class="loginSubmit" type="submit">
			</form>
			<button type="button">
			<%= link_to "Create Account", '/users/new' %></button>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class = "newUser">
<h1>New User</h1>

<%= render 'form' %>
<button type="button">
<%= link_to 'Back', '/' %>
</button>
</div>

app/views/users/show.html.erb
<div class="container" id="userShow">
<p id="notice"><%= notice %></p>
	<div class="row">
	<div class="col-md-12" >
		<p>
		  <strong>First name:</strong>
		  <%= @user.first_name %>
		</p>

		<p>
		  <strong>Last name:</strong>
		  <%= @user.last_name %>
		</p>

		<p>
		  <strong>Email:</strong>
		  <%= @user.email %>
		</p>

		<p>
		  <strong>Password:</strong>
		  <%= @user.password %>
		</p>
		<button type="button">
		<%= link_to 'Check out the posts', posts_path %>
		</button>
	</div>
	</div>
</div>